#' @title Plot a variable in theta_y across Metropolis samples
#'
#' @description \code{theta_y_plot_sample_variable} plots a variable in theta_y (alpha, rho, a, r, or b) across Metropolis samples given a bundle of relevant variables generated by \code{bundle_theta_y_sample}.
#'
#' @param bundle The bundle of variables (see \code{bundle_theta_y_sample})
#' @param variable Which variable to plot
#' @param fileName Filename for pdf save file [optional]

#' @param hp
#'
# @keywords
#' @export
#'
#' @author Michael Holton Price <MichaelHoltonPrice@gmail.com>

theta_y_plot_sample_variable <- function(bundle,variable,decim=1,fileName=NA) {
  ind <- seq(1,length(bundle$theta_yList),by=decim)
  toFile <- !is.na(fileName)
  isOrd <- variable %in% c('alpha','rho')
 options(warn=-1) # in case J < 3
  if(isOrd) {
    colVect <- brewer.pal(n=bundle$hp$J,name='Set1')
  } else {
    colVect <- brewer.pal(n=bundle$hp$K,name='Set1')
  }
  options(warn=0)

  valList <- lapply(bundle$theta_yList,function(x){get(variable,x)})

  yMin <- Inf
  yMax <- -Inf
  yMin <- min(yMin,unlist(valList))
  yMax <- max(yMax,unlist(valList))

  if(bundle$haveKnown) {
    v <- get(variable,bundle$known$theta_y)
    yMin <- min(yMin,v)
    yMax <- max(yMax,v)
  }
  if(toFile) {
    pdf(fileName)
  }
  plot(1,type="n",xlab="Sample", ylab=variable,xlim=c(0,max(ind)),ylim=c(yMin,yMax))
  if(isOrd) {
    for(j in 1:bundle$hp$J) {
      points(ind,sapply(valList,function(x){x[j]})[ind],col=colVect[j],pch=20)
      if(bundle$haveKnown) {
        lines(c(0,max(ind)),c(1,1)*v[j],col=colVect[j],lwd=3)
      }
    }
  }

  if(toFile) {
    dev.off()
  }
}
